// <auto-generated />
using System;
using HeroSSID.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeroSSID.Data.Migrations
{
    [DbContext(typeof(HeroDbContext))]
    partial class HeroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeroSSID.Data.Entities.DidEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DidDocumentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("did_document_json");

                    b.Property<string>("DidIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("did_identifier");

                    b.Property<byte[]>("KeyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("key_fingerprint");

                    b.Property<byte[]>("PrivateKeyEd25519Encrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("private_key_ed25519_encrypted");

                    b.Property<byte[]>("PublicKeyEd25519")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key_ed25519");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("DidIdentifier")
                        .IsUnique()
                        .HasDatabaseName("idx_dids_identifier");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_dids_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_dids_tenant");

                    b.HasIndex("TenantId", "KeyFingerprint")
                        .HasDatabaseName("idx_dids_tenant_key_fingerprint");

                    b.ToTable("dids", null, t =>
                        {
                            t.HasCheckConstraint("chk_did_status", "status IN ('active', 'deactivated')");
                        });
                });

            modelBuilder.Entity("HeroSSID.Data.Entities.VerifiableCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CredentialJwt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credential_jwt");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("credential_type");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("HolderDidId")
                        .HasColumnType("uuid")
                        .HasColumnName("holder_did_id");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("IssuerDidId")
                        .HasColumnType("uuid")
                        .HasColumnName("issuer_did_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CredentialType")
                        .HasDatabaseName("idx_credentials_type");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_credentials_expires_at")
                        .HasFilter("expires_at IS NOT NULL");

                    b.HasIndex("HolderDidId")
                        .HasDatabaseName("idx_credentials_holder");

                    b.HasIndex("IssuedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_credentials_issued_at");

                    b.HasIndex("IssuerDidId")
                        .HasDatabaseName("idx_credentials_issuer");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_credentials_tenant");

                    b.HasIndex("TenantId", "CredentialType", "IssuedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_credentials_tenant_type_issued");

                    b.ToTable("verifiable_credentials", null, t =>
                        {
                            t.HasCheckConstraint("chk_credentials_expiration", "expires_at IS NULL OR expires_at > issued_at");
                        });
                });

            modelBuilder.Entity("HeroSSID.Data.Entities.VerifiableCredentialEntity", b =>
                {
                    b.HasOne("HeroSSID.Data.Entities.DidEntity", "HolderDid")
                        .WithMany("HeldCredentials")
                        .HasForeignKey("HolderDidId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credentials_holder");

                    b.HasOne("HeroSSID.Data.Entities.DidEntity", "IssuerDid")
                        .WithMany("IssuedCredentials")
                        .HasForeignKey("IssuerDidId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credentials_issuer");

                    b.Navigation("HolderDid");

                    b.Navigation("IssuerDid");
                });

            modelBuilder.Entity("HeroSSID.Data.Entities.DidEntity", b =>
                {
                    b.Navigation("HeldCredentials");

                    b.Navigation("IssuedCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
